embed_dim = 64
skip_dim = 256
geo_num_heads = 4
sem_num_heads = 2
t_num_heads = 2
mlp_ratio = 4
qkv_bias = True
drop = 0
attn_drop = 0
drop_path = 0.3
s_attn_size = 3
t_attn_size = 1
enc_depth = 6
type_ln = "post"
type_short_path = "hop"

scaler = "standard"
load_external = True
normal_external = False
ext_scaler = "none"
add_time_in_day = True
add_day_in_week = True
batch_size = 16

seed = 0
max_epoch = 300
learner = "adamw"
learning_rate = 0.001
weight_decay = 0.05
lr_decay = True
lr_scheduler = "cosine"
lr_eta_min = 0.0001
lr_decay_ratio = 0.1
lr_warmup_epoch = 5
lr_warmup_init = 0.000001
clip_grad_norm = True
max_grad_norm = 5
use_early_stop = True
patience = 50
step_size = 1562
task_level = 0
use_curriculum_learning = True
random_flip = True
huber_delta = 1
quan_delta = 0.25
bidir = False
far_mask_delta = 5
dtw_delta = 5
set_loss = "masked_mae"
sem_attn_mode = "dynamic"
t_attn_mode = "patch"

num_dgat_rounds = 2
nb_random_features = 16
k_route = 3
patch_sizes = [2, 4, 6, 8]
kernel_sizes = [3, 5, 7]
k_freq = 1
